GET http://localhost:3001/api/persons

###
GET http://localhost:3001/api/persons

###

POST http://localhost:3001/api/persons
content-type: application/json

{
    "name": "VIP 6",
    "number": "116661444411"
}

###

POST http://localhost:3001/api/persons
content-type: application/json

{
    "name": "VIP 2",
    "number": "22222"
}

### test invalid name
POST http://localhost:3001/api/persons
content-type: application/json

{
    "name": "VP",
    "number": "22222"
}

### 
DELETE http://localhost:3001/api/persons/1
