GET http://localhost:3001/api/persons

###
GET http://localhost:3001/api/persons

###

POST http://localhost:3001/api/persons
content-type: application/json

{
    "name": "VIP 1",
    "number": "11111"
}

###

POST http://localhost:3001/api/persons
content-type: application/json

{
    "name": "VIP 2",
    "number": "22222"
}
